### ISSUE TITLE
WKWebView always white

### ISSUE THREAD

**Issue by landnbloc** [s2mr/Elephant#3]
I see that the code says otherwise but for some reason, the webView is always drawing a white background, are you all seeing this as well?  *im using xcode 11 and running on ios13

Appreciate it
Landen

**Comment by landnbloc** [comment]
I solved my issue like so (note: calling .startAnimation() was unneeded  and threw a fatal error if called)

If I knew more about what I'm doing I'd create a pull request 

view.addSubview(svgView)
        svgView.translatesAutoresizingMaskIntoConstraints = false
        NSLayoutConstraint.activate([
            svgView.centerXAnchor.constraint(equalTo: view.centerXAnchor),
            svgView.centerYAnchor.constraint(equalTo: view.centerYAnchor),
            svgView.widthAnchor.constraint(equalToConstant: 400),
            svgView.heightAnchor.constraint(equalToConstant: 400),
        ])
         
        svgView.webView.isOpaque = false
        svgView.webView.backgroundColor = UIColor.clear
        svgView.webView.scrollView.backgroundColor = UIColor.clear

**Comment by s2mr** [comment]
Fixed
